from __future__ import annotations
from typing import Protocol, Any
from dataclasses import dataclass

@dataclass(frozen=True)
class TranscriptionResult:
    text: str
    confidence: float
    language: str
    raw: Any = None

@dataclass(frozen=True)
class BoundingBox:
    x: int
    y: int
    width: int
    height: int
    label: str = ""
    confidence: float = 0.0

@dataclass(frozen=True)
class UIElement:
    name: str
    element_type: str
    bounds: BoundingBox | None = None
    text: str = ""
    enabled: bool = True
    focused: bool = False

@dataclass(frozen=True)
class VisionResult:
    description: str
    elements: tuple[UIElement, ...] = ()
    raw: Any = None

@dataclass(frozen=True)
class BrowserResult:
    success: bool
    url: str = ""
    title: str = ""
    message: str = ""
    data: Any = None

class STTProvider(Protocol):
    def transcribe(self, audio_data: bytes, *, language: str = "auto") -> TranscriptionResult: ...
    def is_available(self) -> bool: ...

class TTSProvider(Protocol):
    def speak(self, text: str, *, language: str = "en") -> None: ...
    def speak_to_bytes(self, text: str, *, language: str = "en") -> bytes: ...
    def is_available(self) -> bool: ...

class VisionProvider(Protocol):
    def analyze(self, image: bytes, prompt: str) -> VisionResult: ...
    def locate_element(self, image: bytes, description: str) -> list[BoundingBox]: ...
    def is_available(self) -> bool: ...

class BrowserProvider(Protocol):
    def navigate(self, url: str) -> BrowserResult: ...
    def screenshot(self) -> bytes: ...
    def click(self, selector: str) -> BrowserResult: ...
    def type_text(self, selector: str, text: str) -> BrowserResult: ...
    def extract_text(self, selector: str | None = None) -> str: ...
    def is_available(self) -> bool: ...

class CredentialProvider(Protocol):
    def get(self, service: str, key: str) -> str | None: ...
    def store(self, service: str, key: str, value: str) -> None: ...
    def delete(self, service: str, key: str) -> None: ...
    def is_available(self) -> bool: ...

class LLMProvider(Protocol):
    def generate(self, prompt: str, *, system: str = "", temperature: float = 0.7) -> str: ...
    def generate_structured(self, prompt: str, schema: dict[str, Any], *, system: str = "") -> dict[str, Any]: ...
    def is_available(self) -> bool: ...

class StorageProvider(Protocol):
    def save(self, key: str, data: bytes) -> None: ...
    def load(self, key: str) -> bytes | None: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def is_available(self) -> bool: ...
