from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Mapping, Protocol


class ExtensionStatus(str, Enum):
    REGISTERED = "registered"
    INITIALIZED = "initialized"
    ACTIVE = "active"
    DISABLED = "disabled"
    ERROR = "error"


@dataclass(frozen=True)
class ExtensionMetadata:
    name: str
    version: str
    category: str
    description: str
    auth_required: bool = False
    status: ExtensionStatus = ExtensionStatus.REGISTERED
    supported_operations: tuple[str, ...] = ()
    extra: dict[str, Any] = field(default_factory=dict)


class GmailExtension(Protocol):
    def search_messages(self, query: str, max_results: int = 10) -> list[dict[str, Any]]: ...
    def send_message(self, to: str, subject: str, body: str) -> bool: ...
    def read_thread(self, thread_id: str) -> dict[str, Any]: ...
    def is_available(self) -> bool: ...


class GoogleDriveExtension(Protocol):
    def search_files(self, name_pattern: str, max_results: int = 10) -> list[dict[str, Any]]: ...
    def upload_file(self, local_path: str, remote_folder: str = "") -> dict[str, Any]: ...
    def download_file(self, file_id: str, destination_path: str) -> bool: ...
    def is_available(self) -> bool: ...


class GitHubExtension(Protocol):
    def list_repositories(self) -> list[str]: ...
    def create_issue(self, repo: str, title: str, body: str) -> dict[str, Any]: ...
    def get_pull_request(self, repo: str, pr_number: int) -> dict[str, Any]: ...
    def is_available(self) -> bool: ...


class NotionExtension(Protocol):
    def search_pages(self, query: str) -> list[dict[str, Any]]: ...
    def create_page(self, parent_id: str, title: str, content: str) -> dict[str, Any]: ...
    def update_page(self, page_id: str, updates: Mapping[str, Any]) -> bool: ...
    def is_available(self) -> bool: ...


class SlackExtension(Protocol):
    def send_message(self, channel: str, text: str) -> bool: ...
    def list_channels(self) -> list[str]: ...
    def read_history(self, channel: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def is_available(self) -> bool: ...


class DiscordExtension(Protocol):
    def send_message(self, channel_id: str, content: str) -> bool: ...
    def list_channels(self, guild_id: str) -> list[dict[str, str]]: ...
    def is_available(self) -> bool: ...


class MCPExtension(Protocol):
    def connect(self, server_params: Mapping[str, Any]) -> bool: ...
    def list_tools(self) -> list[dict[str, Any]]: ...
    def call_tool(self, tool_name: str, arguments: Mapping[str, Any]) -> dict[str, Any]: ...
    def list_resources(self) -> list[dict[str, Any]]: ...
    def is_available(self) -> bool: ...


class CloudExtension(Protocol):
    def list_instances(self, region: str = "") -> list[dict[str, Any]]: ...
    def get_status(self, instance_id: str) -> str: ...
    def restart_instance(self, instance_id: str) -> bool: ...
    def is_available(self) -> bool: ...


class DatabaseExtension(Protocol):
    def query(self, sql_query: str, params: Mapping[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def execute_mutation(self, sql_statement: str, params: Mapping[str, Any] | None = None) -> int: ...
    def get_schema(self, table_name: str = "") -> dict[str, Any]: ...
    def is_available(self) -> bool: ...


class MultiAgentExtension(Protocol):
    def spawn_agent(self, role: str, goal: str) -> str: ...  # returns agent_id
    def send_message(self, agent_id: str, message: str) -> None: ...
    def wait_for_completion(self, agent_id: str, timeout_seconds: float = 60.0) -> dict[str, Any]: ...
    def is_available(self) -> bool: ...


class SchedulerExtension(Protocol):
    def schedule_task(self, task_id: str, cron_or_delay: str, task_payload: Mapping[str, Any]) -> bool: ...
    def cancel_task(self, task_id: str) -> bool: ...
    def list_scheduled(self) -> list[dict[str, Any]]: ...
    def is_available(self) -> bool: ...
